# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import src.reversi_zero.lib.chunk_pb2 as chunk__pb2


class FileServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.upload_play_data = channel.stream_unary(
        '/FileServer/upload_play_data',
        request_serializer=chunk__pb2.Move.SerializeToString,
        response_deserializer=chunk__pb2.Empty.FromString,
        )
    self.download_model_config = channel.unary_stream(
        '/FileServer/download_model_config',
        request_serializer=chunk__pb2.ModelGeneration.SerializeToString,
        response_deserializer=chunk__pb2.Chunk.FromString,
        )
    self.download_model_weight = channel.unary_stream(
        '/FileServer/download_model_weight',
        request_serializer=chunk__pb2.ModelGeneration.SerializeToString,
        response_deserializer=chunk__pb2.Chunk.FromString,
        )
    self.report_resign_false_positive = channel.unary_unary(
        '/FileServer/report_resign_false_positive',
        request_serializer=chunk__pb2.ResignFalsePositive.SerializeToString,
        response_deserializer=chunk__pb2.Empty.FromString,
        )
    self.ask_resign_v = channel.unary_unary(
        '/FileServer/ask_resign_v',
        request_serializer=chunk__pb2.Empty.SerializeToString,
        response_deserializer=chunk__pb2.ResignV.FromString,
        )


class FileServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def upload_play_data(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download_model_config(self, request, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download_model_weight(self, request, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def report_resign_false_positive(self, request, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ask_resign_v(self, request, context):
    # missing associated documentation comment in .proto file
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'upload_play_data': grpc.stream_unary_rpc_method_handler(
          servicer.upload_play_data,
          request_deserializer=chunk__pb2.Move.FromString,
          response_serializer=chunk__pb2.Empty.SerializeToString,
      ),
      'download_model_config': grpc.unary_stream_rpc_method_handler(
          servicer.download_model_config,
          request_deserializer=chunk__pb2.ModelGeneration.FromString,
          response_serializer=chunk__pb2.Chunk.SerializeToString,
      ),
      'download_model_weight': grpc.unary_stream_rpc_method_handler(
          servicer.download_model_weight,
          request_deserializer=chunk__pb2.ModelGeneration.FromString,
          response_serializer=chunk__pb2.Chunk.SerializeToString,
      ),
      'report_resign_false_positive': grpc.unary_unary_rpc_method_handler(
          servicer.report_resign_false_positive,
          request_deserializer=chunk__pb2.ResignFalsePositive.FromString,
          response_serializer=chunk__pb2.Empty.SerializeToString,
      ),
      'ask_resign_v': grpc.unary_unary_rpc_method_handler(
          servicer.ask_resign_v,
          request_deserializer=chunk__pb2.Empty.FromString,
          response_serializer=chunk__pb2.ResignV.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
