# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chunk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chunk.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x63hunk.proto\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"*\n\x04Move\x12\x0b\n\x03\x63ob\x18\x01 \x01(\x0c\x12\n\n\x02pi\x18\x02 \x01(\x0c\x12\t\n\x01z\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"&\n\nResignCtrl\x12\t\n\x01n\x18\x01 \x01(\x05\x12\r\n\x05\x66_p_n\x18\x02 \x01(\x05\"-\n\x0fResignThreshold\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x05\x12\t\n\x01v\x18\x02 \x01(\x02\x32\xee\x01\n\nFileServer\x12%\n\x10upload_play_data\x12\x05.Move\x1a\x06.Empty\"\x00(\x01\x12+\n\x15\x64ownload_model_config\x12\x06.Empty\x1a\x06.Chunk\"\x00\x30\x01\x12+\n\x15\x64ownload_model_weight\x12\x06.Empty\x1a\x06.Chunk\"\x00\x30\x01\x12+\n\x12report_resign_ctrl\x12\x0b.ResignCtrl\x1a\x06.Empty\"\x00\x12\x32\n\x14\x61sk_resign_threshold\x12\x06.Empty\x1a\x10.ResignThreshold\"\x00\x62\x06proto3')
)




_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='Chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=38,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cob', full_name='Move.cob', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pi', full_name='Move.pi', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Move.z', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=82,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=91,
)


_RESIGNCTRL = _descriptor.Descriptor(
  name='ResignCtrl',
  full_name='ResignCtrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='ResignCtrl.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f_p_n', full_name='ResignCtrl.f_p_n', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=131,
)


_RESIGNTHRESHOLD = _descriptor.Descriptor(
  name='ResignThreshold',
  full_name='ResignThreshold',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='ResignThreshold.enabled', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='ResignThreshold.v', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ResignCtrl'] = _RESIGNCTRL
DESCRIPTOR.message_types_by_name['ResignThreshold'] = _RESIGNTHRESHOLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'chunk_pb2'
  # @@protoc_insertion_point(class_scope:Chunk)
  ))
_sym_db.RegisterMessage(Chunk)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
  DESCRIPTOR = _MOVE,
  __module__ = 'chunk_pb2'
  # @@protoc_insertion_point(class_scope:Move)
  ))
_sym_db.RegisterMessage(Move)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'chunk_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

ResignCtrl = _reflection.GeneratedProtocolMessageType('ResignCtrl', (_message.Message,), dict(
  DESCRIPTOR = _RESIGNCTRL,
  __module__ = 'chunk_pb2'
  # @@protoc_insertion_point(class_scope:ResignCtrl)
  ))
_sym_db.RegisterMessage(ResignCtrl)

ResignThreshold = _reflection.GeneratedProtocolMessageType('ResignThreshold', (_message.Message,), dict(
  DESCRIPTOR = _RESIGNTHRESHOLD,
  __module__ = 'chunk_pb2'
  # @@protoc_insertion_point(class_scope:ResignThreshold)
  ))
_sym_db.RegisterMessage(ResignThreshold)



_FILESERVER = _descriptor.ServiceDescriptor(
  name='FileServer',
  full_name='FileServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=181,
  serialized_end=419,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload_play_data',
    full_name='FileServer.upload_play_data',
    index=0,
    containing_service=None,
    input_type=_MOVE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download_model_config',
    full_name='FileServer.download_model_config',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CHUNK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download_model_weight',
    full_name='FileServer.download_model_weight',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CHUNK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='report_resign_ctrl',
    full_name='FileServer.report_resign_ctrl',
    index=3,
    containing_service=None,
    input_type=_RESIGNCTRL,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ask_resign_threshold',
    full_name='FileServer.ask_resign_threshold',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESIGNTHRESHOLD,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVER)

DESCRIPTOR.services_by_name['FileServer'] = _FILESERVER

# @@protoc_insertion_point(module_scope)
